// Automatically generated by astro-icon
// 114de442656ad1b12a6ef04bc2f173a74983bca814815c2a7eed567acd93c162

declare module 'virtual:astro-icon' {
	export type Icon = 
		| "clock"
		| "error"
		| "mail"
		| "map-pin"
		| "menu"
		| "payment_cards/amex"
		| "payment_cards/diner"
		| "payment_cards/discover"
		| "payment_cards/empty"
		| "payment_cards/jcb"
		| "payment_cards/mastercard"
		| "payment_cards/visa"
		| "phone-ring"
		| "search"
		| "socials/facebook"
		| "socials/facebook2"
		| "socials/instagram"
		| "socials/instagram2"
		| "socials/twitter"
		| "socials/twitter2"
		| "usa_flag";
}